pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: DevOps

stages:
  - stage: "Get_latest_build_artifacts"
    jobs:
      - job:
        workspace:
          clean: all
        steps:
          - script: python -m pip install --upgrade pip setuptools wheel requests pyyaml argparse kafka-python
            displayName: 'Install_python_deps'
          - task: Bash@3
            displayName: 'Set_pipeline_environment'
            inputs:
              targetType: 'inline'
              script: |
                  python $SYSTEM_DEFAULTWORKINGDIRECTORY/pipelines/scripts/setup_environment.py
                  bash $SYSTEM_DEFAULTWORKINGDIRECTORY/pipelines/vars/pipeline.env | tr -d "\'"
                  printenv
            env:
              APIUSER: $(devops_apiuser)
              APIPASS: $(devops_apipass)

          - task: Bash@3
            displayName: 'Debug env'
            inputs:
              targetType: 'inline'
              script: |
                printenv
                python $SYSTEM_DEFAULTWORKINGDIRECTORY/pipelines/scripts/create_kafka_topics.py $SYSTEM_DEFAULTWORKINGDIRECTORY/configuration/kafka_topics.yaml

          - task: PythonScript@0
            displayName: 'Create kafka topics'
            inputs:
              scriptSource: 'filePath'
              scriptPath: '$(system.DefaultWorkingDirectory)/pipelines/scripts/create_kafka_topics.py'
              arguments: '$(system.DefaultWorkingDirectory)/configuration/kafka_topics.yaml'